# Target name
target := hola

# Source list *.cpp space separated
source := main.cpp

# Space separated PATH of library find, (Added as -L to the linker)
libpath := 

# Space separated libraries names. Added as -l to the kinker
libraries := 

# Space separated incluid
incpath := /usr/local/include

# Include rules
include rules.mk
